/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pFormularios;
import index.menu;
import java.awt.Font;
import java.awt.Color;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import pClases.ArregloFacturas;
import pClases.Factura;

/**
 *
 * @author katherineambrocio
*/

public final class frmVenta extends javax.swing.JFrame {
  
    
     
    ArregloFacturas f=new ArregloFacturas();
    int num=0;
    /**
     * Creates new form frmMantenimiento
     */
    
    public frmVenta() {
        initComponents();
        DefinirAnchos();
        asignaFecha();
        habilitaCajas(false);
        btnGrabarIngreso.setVisible(false);
        btnGrabarModificado.setVisible(false);
    
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtVendedor = new javax.swing.JTextField();
        txtNfactura = new javax.swing.JTextField();
        txtFechaVenta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnGrabarModificado = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnGrabarIngreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFacturas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 660));
        setSize(new java.awt.Dimension(630, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 660));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 660));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentas.setFont(new java.awt.Font("New York Medium", 1, 36)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(51, 51, 51));
        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/icons8-gráfico-combinado-50.png"))); // NOI18N
        lblVentas.setText("REGISTRO DE VENTAS ");
        jPanel1.add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 660, 110));

        txtMonto.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        txtMonto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "PRECIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("New York", 1, 12))); // NOI18N
        txtMonto.setOpaque(true);
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 170, 50));

        txtVendedor.setFont(new java.awt.Font("New York", 0, 12)); // NOI18N
        txtVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("New York", 1, 12))); // NOI18N
        txtVendedor.setOpaque(true);
        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 230, 50));

        txtNfactura.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        txtNfactura.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "N° PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("New York", 1, 12))); // NOI18N
        txtNfactura.setOpaque(true);
        jPanel1.add(txtNfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, 50));

        txtFechaVenta.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        txtFechaVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "FECHA ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("New York", 1, 12))); // NOI18N
        txtFechaVenta.setOpaque(true);
        jPanel1.add(txtFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 170, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "OPCIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("New York", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnEliminar.setMaximumSize(new java.awt.Dimension(57, 57));
        btnEliminar.setMinimumSize(new java.awt.Dimension(57, 57));
        btnEliminar.setOpaque(true);
        btnEliminar.setPreferredSize(new java.awt.Dimension(57, 57));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verificar.png"))); // NOI18N
        btnListado.setMaximumSize(new java.awt.Dimension(57, 57));
        btnListado.setMinimumSize(new java.awt.Dimension(57, 57));
        btnListado.setOpaque(true);
        btnListado.setPreferredSize(new java.awt.Dimension(57, 57));
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnConsultar.setMaximumSize(new java.awt.Dimension(57, 57));
        btnConsultar.setMinimumSize(new java.awt.Dimension(57, 57));
        btnConsultar.setOpaque(true);
        btnConsultar.setPreferredSize(new java.awt.Dimension(57, 57));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnGrabarModificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnGrabarModificado.setMaximumSize(new java.awt.Dimension(57, 57));
        btnGrabarModificado.setMinimumSize(new java.awt.Dimension(57, 57));
        btnGrabarModificado.setOpaque(true);
        btnGrabarModificado.setPreferredSize(new java.awt.Dimension(57, 57));
        btnGrabarModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarModificadoActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnModificar.setMaximumSize(new java.awt.Dimension(57, 57));
        btnModificar.setMinimumSize(new java.awt.Dimension(57, 57));
        btnModificar.setOpaque(true);
        btnModificar.setPreferredSize(new java.awt.Dimension(57, 57));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnRegistrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnRegistrar.setMaximumSize(new java.awt.Dimension(57, 57));
        btnRegistrar.setMinimumSize(new java.awt.Dimension(57, 57));
        btnRegistrar.setOpaque(true);
        btnRegistrar.setPreferredSize(new java.awt.Dimension(57, 57));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnGrabarIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        btnGrabarIngreso.setMaximumSize(new java.awt.Dimension(57, 57));
        btnGrabarIngreso.setMinimumSize(new java.awt.Dimension(57, 57));
        btnGrabarIngreso.setOpaque(true);
        btnGrabarIngreso.setPreferredSize(new java.awt.Dimension(57, 57));
        btnGrabarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGrabarModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGrabarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnGrabarModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsultar, btnEliminar, btnGrabarModificado, btnListado, btnModificar, btnRegistrar});

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 150, 560));

        tFacturas.setBackground(new java.awt.Color(204, 204, 204));
        tFacturas.setForeground(new java.awt.Color(153, 153, 153));
        tFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°  PRODUCTO", "FECHA", "CLIENTE", "PRECIO"
            }
        ));
        tFacturas.setGridColor(new java.awt.Color(0, 0, 0));
        tFacturas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tFacturas.setSelectionForeground(new java.awt.Color(255, 204, 204));
        tFacturas.setShowGrid(true);
        tFacturas.setSurrendersFocusOnKeystroke(true);
        tFacturas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tFacturas);
        tFacturas.getTableHeader().setFont(new Font("New York", Font.BOLD, 11));
        tFacturas.getTableHeader().setForeground(new Color(255,255,204));
        tFacturas.getTableHeader().setOpaque(true);
        tFacturas.getTableHeader().setBackground(new Color(0, 153, 153));

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 600, 230));

        jButton1.setFont(new java.awt.Font("New York", 1, 13)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 100, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleName("");

        setBounds(0, 0, 881, 688);
    }// </editor-fold>//GEN-END:initComponents

    
    public JTable gettFacturas() {
        return tFacturas;
    }

    public JTextField getTxtFechaVenta() {
        return txtFechaVenta;
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        txtNfactura.setText(""+generaNumero());
        asignaFecha();
        txtVendedor.requestFocus();
        habilitaCajas(true);
        txtVendedor.setEditable(true);
        txtMonto.setEditable(true);
        txtVendedor.setText("");
        txtMonto.setText("");
        btnRegistrar.setVisible(false);
        btnGrabarIngreso.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        try{
        limpiaCajas();
        limpiaMatriz();
        int buscoFactura=Integer.parseInt(JOptionPane.showInputDialog(null,
                "Ingrese un numero de Factura:"));
//objeto fact que busca el numero de factura en el ArrayList f
        Factura fact=f.buscar(buscoFactura);
        if (fact!=null){
            tFacturas.setValueAt(fact.getNfactura(), 0, 0);
            tFacturas.setValueAt(fact.getfecha(), 0, 1);
            tFacturas.setValueAt(fact.getVendedor(), 0, 2);
            tFacturas.setValueAt(fact.getMonto(), 0, 3);
        }else
         JOptionPane.showMessageDialog(null,"Factura NO encontrada","Confirmacion",
                 JOptionPane.ERROR_MESSAGE);
        } catch(Exception ex){
       JOptionPane.showMessageDialog(null,"Error de Entrada de Datos",
      "Confirmacion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
         limpiaCajas();
         limpiaMatriz();
         btnModificar.setVisible(false);
         btnGrabarModificado.setVisible(true);
 
         int buscoFactura=Integer.parseInt(JOptionPane.showInputDialog(null,
                "Ingrese un numero de Factura:"));
//objeto fact que busca el numero de factura en el ArrayList f
        Factura fact=f.buscar(buscoFactura);
        if (fact!=null){
         tFacturas.setValueAt(fact.getNfactura(), 0, 0);
         tFacturas.setValueAt(fact.getfecha(), 0, 1);
         tFacturas.setValueAt(fact.getVendedor(), 0, 2);
         tFacturas.setValueAt(fact.getMonto(), 0, 3);
    
         txtNfactura.setText(""+fact.getNfactura());
         txtFechaVenta.setText(fact.getfecha());
         txtVendedor.setText(fact.getVendedor());
         txtMonto.setText(""+fact.getMonto());
    
         habilitaCajas(true);
         txtNfactura.setEditable(false);
         txtFechaVenta.setEditable(false);
        }else
         JOptionPane.showMessageDialog(null,"Factura NO encontrada",
        "Confirmacion",JOptionPane.ERROR_MESSAGE);
        }catch(Exception ex){   
        JOptionPane.showMessageDialog(null,"Factura NO encontrada",
       "Confirmacion",JOptionPane.ERROR_MESSAGE);
        btnModificar.setVisible(true);
        btnGrabarModificado.setVisible(false);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         try{
         int buscoFactura=Integer.parseInt(JOptionPane.showInputDialog(null,
        "Ingrese un numero de Factura a Eliminar:"));
         //objeto fact que busca el numero de factura en el ArrayList f
        Factura fact=f.buscar(buscoFactura);
        if (fact!=null){
           f.eliminar(fact);
           JOptionPane.showMessageDialog(null,"Factura Eliminada",
        "Confirmacion",JOptionPane.INFORMATION_MESSAGE);
           listar();
         }else
         JOptionPane.showMessageDialog(null,
        "NO existe el Numero de Factura ingresada",
                "Confirmacion",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception ex){
         JOptionPane.showMessageDialog(null,
        "NO existe el Numero de Factura ingresada","Confirmacion",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnListadoActionPerformed

    private void btnGrabarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarIngresoActionPerformed
        // TODO add your handling code here:
         try{
         habilitaCajas(false);
         btnRegistrar.setVisible(true);
         btnGrabarIngreso.setVisible(false);
  
     Factura fact=new Factura(getNumFact(),getFecha(),getVendedor(),getMonto());
     f.agregar(fact);
     listar();
     JOptionPane.showMessageDialog(null,
     "Factura ingresada correctamente",
     "Confirmacion",JOptionPane.INFORMATION_MESSAGE);
      }catch(Exception ex){
     JOptionPane.showMessageDialog(null,"Error de Ingreso de Datos","Error",
             JOptionPane.ERROR_MESSAGE);
     num--;
         }
    }//GEN-LAST:event_btnGrabarIngresoActionPerformed

    private void btnGrabarModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarModificadoActionPerformed
        // TODO add your handling code here:
        try{
        Factura fact=f.buscar(getNumFact());
        fact.setVendedor(getVendedor());
        fact.setMonto(getMonto());
        JOptionPane.showMessageDialog(null,
         "Factura Modificada Correctamente",
"Confirmacion",JOptionPane.INFORMATION_MESSAGE);
        listar();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,
"Ocurrio un error al intentar Grabar",
"Confirmacion",JOptionPane.INFORMATION_MESSAGE);
        }
        btnGrabarModificado.setVisible(false);
         btnModificar.setVisible(true);
        

    }//GEN-LAST:event_btnGrabarModificadoActionPerformed

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu m1 = new menu();
            m1.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
//Metodos que capturan los valores ingresados por el usuario
   private void DefinirAnchos() {
      TableColumn columna;
             columna=tFacturas.getColumnModel().getColumn(0);
             columna.setPreferredWidth(30);
             columna=tFacturas.getColumnModel().getColumn(1);
             columna.setPreferredWidth(50);
             columna=tFacturas.getColumnModel().getColumn(2);
             columna.setPreferredWidth(150);
             columna=tFacturas.getColumnModel().getColumn(3);
             columna.setPreferredWidth(70);
        tFacturas.getTableHeader().setReorderingAllowed(false);
        tFacturas.getTableHeader().setResizingAllowed(false);
    }

    private void asignaFecha() {
        GregorianCalendar cal=new GregorianCalendar();
        txtFechaVenta.setText(cal.get(cal.DAY_OF_MONTH)+"/"
        +cal.MONTH+"/"
        +cal.get(cal.YEAR));
    }
    
        
//Metodo que bloquea y desbloquea los controles JTextField    
     void habilitaCajas(boolean opcion){
         txtNfactura.setEditable(opcion);
         txtVendedor.setEditable(opcion);
         txtMonto.setEditable(opcion);
         txtFechaVenta.setEditable(opcion);
     }

//Metodo que limpia los controles JTextField
     void limpiaCajas(){
         txtNfactura.setText("");
         txtVendedor.setText("");
         txtFechaVenta.setText("");
         txtMonto.setText("");
     }
 //Metodo que limpia el control tFacturas
     void limpiaMatriz(){
     for(int i=0;i<10;i++){
     tFacturas.setValueAt("", i, 0);
     tFacturas.setValueAt("", i, 1);
     tFacturas.setValueAt("", i, 2); 
     tFacturas.setValueAt("", i, 3);
          }
     }
    
//Metodo que genera el numero de factura
     public int generaNumero(){
         num++;
     return num; }
     
  
     public int getNumFact(){
         return Integer.parseInt(txtNfactura.getText());
     }
     
     public String getFecha(){
         return txtFechaVenta.getText();
     }
     
     public String getVendedor(){
         return txtVendedor.getText();
     }
     
     public double getMonto(){
     return Double.parseDouble(txtMonto.getText());
     }


//Metodo que lista las facturas en el control tFacturas
     void listar(){
  
         if (f.getTamaño()>0){
             for(int i=0;i<f.getTamaño();i++){
             Factura fact=f.obtener(i);
             tFacturas.setValueAt(fact.getNfactura(),i,0);
             tFacturas.setValueAt(fact.getfecha(), i, 1);
             tFacturas.setValueAt(fact.getVendedor(), i, 2);
             tFacturas.setValueAt(fact.getMonto(), i, 3);
             }
         } else {
         JOptionPane.showMessageDialog(this,
         "No hay facturas registradas",
         "Confirmacion",JOptionPane.INFORMATION_MESSAGE);
         limpiaMatriz();
         } 
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabarIngreso;
    private javax.swing.JButton btnGrabarModificado;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JTable tFacturas;
    private javax.swing.JTextField txtFechaVenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNfactura;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables

 


  
}
