/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFormularios;

import index.menu;
import javax.swing.ImageIcon;

/**
 *
 * @author katherineambrocio
 */
public class Informe extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioPropuesto1
     */
    public Informe() {
        initComponents();
        //ImageIcon image1 = new ImageIcon("src/main/java/Iconos/calcular.png");
       // btncalcular.setIcon(image1);
       // ImageIcon image2 = new ImageIcon("src/main/java/Iconos/nuevo.png");
        //btnnuevo.setIcon(image2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jSlider1 = new javax.swing.JSlider();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        btncalcular = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblencabezado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfa = new javax.swing.JTextField();
        tfd = new javax.swing.JTextField();
        lblta = new javax.swing.JLabel();
        aporteAcc = new javax.swing.JTextField();
        tfi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblan = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        C1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        aporteAcc1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A1 = new javax.swing.JTextField();
        tfd1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfa7 = new javax.swing.JTextField();
        tfi2 = new javax.swing.JTextField();
        tfi3 = new javax.swing.JTextField();
        tfd3 = new javax.swing.JTextField();
        aporteAcc4 = new javax.swing.JTextField();
        tfa8 = new javax.swing.JTextField();
        tfa9 = new javax.swing.JTextField();
        tfa10 = new javax.swing.JTextField();
        CU2 = new javax.swing.JTextField();
        aporteAcc5 = new javax.swing.JTextField();
        aporteAcc6 = new javax.swing.JTextField();
        RA = new javax.swing.JTextField();
        aporteAcc8 = new javax.swing.JTextField();
        tfd5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CU1 = new javax.swing.JTextField();
        tfd6 = new javax.swing.JTextField();
        RAe = new javax.swing.JTextField();
        tfd8 = new javax.swing.JTextField();
        tfd9 = new javax.swing.JTextField();
        ER = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        CAP = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        CAAP = new javax.swing.JTextField();
        tfd12 = new javax.swing.JTextField();
        tfd13 = new javax.swing.JTextField();
        tfd14 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfd18 = new javax.swing.JTextField();
        tfd19 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        tfd23 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        S1 = new javax.swing.JTextField();
        tfd30 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAREA 3 - EJERCICIO 2");
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("Cuota");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncalcular.setBackground(new java.awt.Color(19, 161, 243));
        btncalcular.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btncalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/icons8-mantenimiento-50.png"))); // NOI18N
        btncalcular.setText("CALCULAR");
        btncalcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        jPanel3.add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 158, 70));

        btnnuevo.setBackground(new java.awt.Color(19, 161, 243));
        btnnuevo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/icons8-mano-con-pluma-50.png"))); // NOI18N
        btnnuevo.setText("NUEVO");
        btnnuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnnuevo.setPreferredSize(new java.awt.Dimension(137, 54));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 166, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblencabezado.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblencabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblencabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/icons8-estimar-50.png"))); // NOI18N
        lblencabezado.setText("INFORME");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTADO DE CAMBIOS EN EL PATRIMONIO NETO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblencabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblencabezado)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1175, -1));

        tfa.setBackground(new java.awt.Color(204, 204, 204));
        tfa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 150, 30));

        tfd.setBackground(new java.awt.Color(204, 204, 204));
        tfd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 150, 30));

        lblta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel3.add(lblta, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 436, 150, -1));

        aporteAcc.setBackground(new java.awt.Color(204, 204, 204));
        aporteAcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aporteAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(aporteAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, 30));

        tfi.setBackground(new java.awt.Color(204, 204, 204));
        tfi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, 30));

        jLabel10.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("REVALUACIÓN DE TERRENO");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 184, 30));

        lblan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 150, 20));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("CAPITAL");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 40));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("C. ADICIONAL");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 124, 40));

        C1.setBackground(new java.awt.Color(204, 204, 204));
        C1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        C1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 150, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("EXCEDENTE DE REV.");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 160, 40));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("RESERVAS");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 150, 40));

        jLabel21.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("DISTRIBUCIÓN DE DIVIDENDOS");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        aporteAcc1.setBackground(new java.awt.Color(204, 204, 204));
        aporteAcc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aporteAcc1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(aporteAcc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 150, 30));

        C2.setBackground(new java.awt.Color(204, 204, 204));
        C2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        C2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C2.setOpaque(true);
        jPanel3.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 150, 30));

        A2.setBackground(new java.awt.Color(204, 204, 204));
        A2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A2.setOpaque(true);
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel3.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 150, 30));

        A1.setBackground(new java.awt.Color(204, 204, 204));
        A1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A1.setOpaque(true);
        jPanel3.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 150, 30));

        tfd1.setBackground(new java.awt.Color(204, 204, 204));
        tfd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 150, 30));

        jLabel22.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("RETIRO DE ACCIONISTAS");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 184, 30));

        tfa7.setBackground(new java.awt.Color(204, 204, 204));
        tfa7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfa7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 150, 30));

        tfi2.setBackground(new java.awt.Color(204, 204, 204));
        tfi2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfi2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 150, 30));

        tfi3.setBackground(new java.awt.Color(204, 204, 204));
        tfi3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfi3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 150, 30));

        tfd3.setBackground(new java.awt.Color(204, 204, 204));
        tfd3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 150, 30));

        aporteAcc4.setBackground(new java.awt.Color(204, 204, 204));
        aporteAcc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aporteAcc4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(aporteAcc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 150, 30));

        tfa8.setBackground(new java.awt.Color(204, 204, 204));
        tfa8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfa8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 150, 30));

        tfa9.setBackground(new java.awt.Color(204, 204, 204));
        tfa9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfa9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 150, 30));

        tfa10.setBackground(new java.awt.Color(204, 204, 204));
        tfa10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfa10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfa10ActionPerformed(evt);
            }
        });
        jPanel3.add(tfa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 150, 30));

        CU2.setBackground(new java.awt.Color(204, 204, 204));
        CU2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CU2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CU2.setOpaque(true);
        jPanel3.add(CU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 150, 30));

        aporteAcc5.setBackground(new java.awt.Color(204, 204, 204));
        aporteAcc5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aporteAcc5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(aporteAcc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 150, 30));

        aporteAcc6.setBackground(new java.awt.Color(204, 204, 204));
        aporteAcc6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aporteAcc6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(aporteAcc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 150, 30));

        RA.setBackground(new java.awt.Color(204, 204, 204));
        RA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RA.setOpaque(true);
        jPanel3.add(RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 150, 30));

        aporteAcc8.setBackground(new java.awt.Color(204, 204, 204));
        aporteAcc8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aporteAcc8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(aporteAcc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 150, 30));

        tfd5.setBackground(new java.awt.Color(204, 204, 204));
        tfd5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 150, 30));

        jLabel23.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("APORTE DE NUEVOS SOCIOS");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 184, -1));

        jLabel24.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("CAPITALIZACIÓN DE UTILIDADES");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel25.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("UTILIDAD DEL EJERCICIO");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        CU1.setBackground(new java.awt.Color(204, 204, 204));
        CU1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CU1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CU1.setOpaque(true);
        jPanel3.add(CU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 150, 30));

        tfd6.setBackground(new java.awt.Color(204, 204, 204));
        tfd6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 150, 30));

        RAe.setBackground(new java.awt.Color(204, 204, 204));
        RAe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RAe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RAe.setOpaque(true);
        jPanel3.add(RAe, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, 150, 30));

        tfd8.setBackground(new java.awt.Color(204, 204, 204));
        tfd8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 150, 30));

        tfd9.setBackground(new java.awt.Color(204, 204, 204));
        tfd9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 150, 30));

        ER.setBackground(new java.awt.Color(204, 204, 204));
        ER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ER.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERActionPerformed(evt);
            }
        });
        jPanel3.add(ER, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 150, 30));

        jLabel26.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("CAPITALIZAR APORTE PRIMA");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 199, -1));

        CAP.setBackground(new java.awt.Color(204, 204, 204));
        CAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CAP.setOpaque(true);
        CAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAPActionPerformed(evt);
            }
        });
        jPanel3.add(CAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 150, 30));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("CAPITAL");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 150, 40));

        CAAP.setBackground(new java.awt.Color(204, 204, 204));
        CAAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CAAP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CAAP.setOpaque(true);
        jPanel3.add(CAAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 150, 30));

        tfd12.setBackground(new java.awt.Color(204, 204, 204));
        tfd12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 150, 30));

        tfd13.setBackground(new java.awt.Color(204, 204, 204));
        tfd13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd13, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 150, 30));

        tfd14.setBackground(new java.awt.Color(204, 204, 204));
        tfd14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 150, 30));

        jLabel28.setFont(new java.awt.Font("New York Small", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("TRANSFERENCIA A REV. LEGAL");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("R. ACUMULADOS");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 131, 40));

        tfd18.setBackground(new java.awt.Color(204, 204, 204));
        tfd18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 150, 30));

        tfd19.setBackground(new java.awt.Color(204, 204, 204));
        tfd19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfd19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd19ActionPerformed(evt);
            }
        });
        jPanel3.add(tfd19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 150, 30));

        R1.setBackground(new java.awt.Color(204, 204, 204));
        R1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        R1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R1.setOpaque(true);
        jPanel3.add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, 150, 30));

        tfd23.setBackground(new java.awt.Color(204, 204, 204));
        tfd23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 150, 30));

        jLabel29.setFont(new java.awt.Font("New York Medium", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("SALDO");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 150, 40));

        S1.setBackground(new java.awt.Color(153, 204, 255));
        S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1ActionPerformed(evt);
            }
        });
        jPanel3.add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 150, 30));

        tfd30.setBackground(new java.awt.Color(204, 204, 204));
        tfd30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(tfd30, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 150, 30));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("New York", 1, 13)); // NOI18N
        jButton1.setText("MENU");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, 100, 30));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfa10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfa10ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        
        ER.setText("");
        C1.setText("");
        C2.setText("");
        A1.setText("");
        A2.setText("");
        RA.setText("");
        CU1.setText("");
        CU2.setText("");
        RAe.setText("");
        CAAP.setText("");
        CAP.setText("");
        R1.setText("");
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        double exrev,cap,capAd,ap1,ap2,resac,capu1,capu2,ue, cap1,cap2,tr,T1=0;
        
   
        exrev = Double.parseDouble(ER.getText());
        cap = Double.parseDouble(C1.getText());
        capAd = Double.parseDouble(C2.getText());
        ap1 = Double.parseDouble(A1.getText());
        ap2 = Double.parseDouble(A2.getText());
        resac = (-1)* Double.parseDouble(RA.getText());
        capu1 = Double.parseDouble(CU1.getText());
        capu2 = (-1)* Double.parseDouble(CU2.getText());
        ue= Double.parseDouble(RAe.getText());
        cap1= (-1)*Double.parseDouble(CAAP.getText());
        cap2= Double.parseDouble(CAP.getText());
        tr= Double.parseDouble(R1.getText());
      
        T1 = exrev+cap+capAd+ap1+ap2+resac+capu1+capu2+ue+cap1+cap2+tr;
        S1.setText(""+T1);
    }//GEN-LAST:event_btncalcularActionPerformed

    private void tfd19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd19ActionPerformed

    private void S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S1ActionPerformed

    private void CAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAPActionPerformed

    private void ERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ERActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu m1 = new menu();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField CAAP;
    private javax.swing.JTextField CAP;
    private javax.swing.JTextField CU1;
    private javax.swing.JTextField CU2;
    private javax.swing.JTextField ER;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField RA;
    private javax.swing.JTextField RAe;
    private javax.swing.JTextField S1;
    private javax.swing.JTextField aporteAcc;
    private javax.swing.JTextField aporteAcc1;
    private javax.swing.JTextField aporteAcc4;
    private javax.swing.JTextField aporteAcc5;
    private javax.swing.JTextField aporteAcc6;
    private javax.swing.JTextField aporteAcc8;
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnnuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblan;
    private javax.swing.JLabel lblencabezado;
    private javax.swing.JLabel lblta;
    private javax.swing.JTextField tfa;
    private javax.swing.JTextField tfa10;
    private javax.swing.JTextField tfa7;
    private javax.swing.JTextField tfa8;
    private javax.swing.JTextField tfa9;
    private javax.swing.JTextField tfd;
    private javax.swing.JTextField tfd1;
    private javax.swing.JTextField tfd12;
    private javax.swing.JTextField tfd13;
    private javax.swing.JTextField tfd14;
    private javax.swing.JTextField tfd18;
    private javax.swing.JTextField tfd19;
    private javax.swing.JTextField tfd23;
    private javax.swing.JTextField tfd3;
    private javax.swing.JTextField tfd30;
    private javax.swing.JTextField tfd5;
    private javax.swing.JTextField tfd6;
    private javax.swing.JTextField tfd8;
    private javax.swing.JTextField tfd9;
    private javax.swing.JTextField tfi;
    private javax.swing.JTextField tfi2;
    private javax.swing.JTextField tfi3;
    // End of variables declaration//GEN-END:variables
}
