/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pjarraylist;

import javax.swing.JOptionPane;
import pFormularios.frmVenta;
import index.menu;
import pDao.LoginDAO;
import pModelo.Usuario;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */    
    
    private LoginDAO loginDAO;
    
    public Login() {
        initComponents();
        this.loginDAO = new LoginDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblusu = new javax.swing.JLabel();
        btningresar = new javax.swing.JToggleButton();
        lblcontra = new javax.swing.JLabel();
        tfusu = new javax.swing.JTextField();
        tfcontra = new javax.swing.JPasswordField();
        lblusu1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblencab = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusu.setBackground(new java.awt.Color(0, 153, 204));
        lblusu.setFont(new java.awt.Font("New York Medium", 0, 24)); // NOI18N
        lblusu.setForeground(new java.awt.Color(51, 51, 51));
        lblusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusu.setText("INICIAR SESIÓN");
        jPanel2.add(lblusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 231, 43));

        btningresar.setBackground(new java.awt.Color(19, 161, 243));
        btningresar.setFont(new java.awt.Font("New York Medium", 1, 18)); // NOI18N
        btningresar.setForeground(new java.awt.Color(255, 255, 255));
        btningresar.setText("LOGIN");
        btningresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btningresar.setOpaque(true);
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        jPanel2.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 160, 50));

        lblcontra.setBackground(new java.awt.Color(0, 102, 153));
        lblcontra.setFont(new java.awt.Font("New York Medium", 0, 18)); // NOI18N
        lblcontra.setForeground(new java.awt.Color(51, 51, 51));
        lblcontra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcontra.setText("CONTRASEÑA");
        jPanel2.add(lblcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 180, 40));

        tfusu.setBackground(new java.awt.Color(204, 204, 255));
        tfusu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfusu.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        tfusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusuActionPerformed(evt);
            }
        });
        jPanel2.add(tfusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 210, 32));

        tfcontra.setBackground(new java.awt.Color(204, 204, 255));
        tfcontra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfcontra.setToolTipText("");
        tfcontra.setBorder(null);
        tfcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcontraActionPerformed(evt);
            }
        });
        jPanel2.add(tfcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 210, 30));

        lblusu1.setBackground(new java.awt.Color(0, 153, 204));
        lblusu1.setFont(new java.awt.Font("New York Medium", 0, 18)); // NOI18N
        lblusu1.setForeground(new java.awt.Color(51, 51, 51));
        lblusu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusu1.setText("USUARIO");
        jPanel2.add(lblusu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 43));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 267, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 267, 10));

        lblencab.setFont(new java.awt.Font("New York Medium", 0, 36)); // NOI18N
        lblencab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblencab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/apple1.png"))); // NOI18N
        lblencab.setText("SISTEMA DE VENTA E INVENTARIO");
        jPanel2.add(lblencab, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 860, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/favicon.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 490, 60));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 490, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 978, 626));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusuActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
        
        Usuario user = new Usuario();
        user.setUsuario(tfusu.getText());
        user.setContrasena(String.valueOf(tfcontra.getPassword()));
        
        boolean rpta = this.loginDAO.iniciarSesion(user);
        
        if (!rpta) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos.");
        } else {
            JOptionPane.showMessageDialog(this, "El GRUPO3 te da la bienvenida");
            menu m1 = new menu();
            m1.setVisible(true);
            this.setVisible(false);
        }

        
    }//GEN-LAST:event_btningresarActionPerformed

    private void tfcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcontraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btningresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblcontra;
    private javax.swing.JLabel lblencab;
    private javax.swing.JLabel lblusu;
    private javax.swing.JLabel lblusu1;
    private javax.swing.JPasswordField tfcontra;
    private javax.swing.JTextField tfusu;
    // End of variables declaration//GEN-END:variables
}
